name: smarthome
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Check Syntax
      run: find Central/ -name '*.py' | xargs python -m py_compile
